// <auto-generated />
namespace ValidacionTelefonica.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class CatalogoCLN : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(CatalogoCLN));
        
        string IMigrationMetadata.Id
        {
            get { return "202302201809399_Catalogo CLN"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
